{
 "title": "Docker and Host monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total, job)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total, instance)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Host CPU load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:.*\"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{instance=~\"$node:.*\"}))",
     "legendFormat": "Load1"
    },
    {
     "expr": "node_load5{instance=~\"$node:.*\"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{instance=~\"$node:.*\"}))",
     "legendFormat": "Load5"
    },
    {
     "expr": "node_load15{instance=~\"$node:.*\"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{instance=~\"$node:.*\"}))",
     "legendFormat": "Load15"
    }
   ]
  },
  {
   "title": "Network trafic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$node.*\" }[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "-sum(rate(node_network_transmit_bytes_total{instance=~\"$node.*\" }[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Node cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$node:.*\"}[$interval])) * 100",
     "legendFormat": "Cpu usage"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-sum(rate(node_disk_read_bytes_total{instance=~\"$node:.*\"}[$interval])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$node:.*\"}[$interval])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\", instance=~\"$node:.*\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:.*\"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{instance=~\"$node:.*\"}))"
    }
   ]
  },
  {
   "title": "Usage Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".+\", job=\"$job\", instance=~\"$node:.*\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{name=~\".+\", job=\"$job\", instance=~\"$node:.*\"}[1m])) by (name) * 100",
     "legendFormat": "{{ name }} "
    }
   ]
  },
  {
   "title": "Network received by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\", job=\"$job\", instance=~\"$node:.*\"}[$interval])) by (name)",
     "legendFormat": "{{ name }} "
    }
   ]
  },
  {
   "title": "Network sent by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\", job=\"$job\", instance=~\"$node:.*\" }[$interval])) by (name)",
     "legendFormat": "{{ name }} "
    }
   ]
  },
  {
   "title": "Memory usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".+\", job=\"$job\", instance=~\"$node:.*\"}",
     "legendFormat": "{{ name }} "
    }
   ]
  },
  {
   "title": "Network swap by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_swap{name=~\".+\", job=\"$job\", instance=~\"$node:.*\"}) by (name) * 100",
     "legendFormat": "{{ name }} "
    }
   ]
  }
 ]
}