# Generated by Django 4.2.27 on 2025-12-04 07:36

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[utils.validators.validate_cpf], verbose_name='CPF')),
                ('telefone', models.CharField(max_length=11, unique=True, validators=[utils.validators.validate_digits])),
            ],
        ),
    ]
