# Generated by Django 4.2.27 on 2025-12-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_entrega_entregador_farmacia_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='entregador',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
