# Generated by Django 4.2.27 on 2025-12-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_email_alter_entregador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Cliente escolhendo'), (1, 'Solicitado'), (2, 'Sendo separado'), (3, 'A caminho'), (4, 'Entregue')]),
        ),
    ]
