# Generated by Django 4.2.27 on 2025-12-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_pedido_entrega_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
